name: Consume Artifact
on:
  push:
    branches:
      - main  
jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "Produce Artifact" # Name of the workflow that produced the artifact
          run_id: ${{ github.event.workflow_run.id }} # ID of the workflow run that produced the artifact
          name: my-markdown-file # Name of the artifact to download
          path: artifacts